server:
  port: 8090
spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: ATTENDENCE-SERVICE
          uri: lb://ATTENDENCE-SERVICE
          predicates:
            - Path=/sm/attendence/**
          filters:
           - AuthenticationFilter  
            
        - id: SMSUSERS-SERVICE
          uri: lb://SMSUSERS-SERVICE
          predicates:
            - Path=/sm/user/**
          filters:
           - AuthenticationFilter
           
        - id: ENROLLMENT-SERVICE
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/ms/enrollment/**
          filters:
           - AuthenticationFilter
            
        - id: EXAMS-SERVICE
          uri: lb://EXAMS-SERVICE
          predicates:
            - Path=/ms/exams/**
          filters:
           - AuthenticationFilter
           
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/bs/customer/**
          filters:
           - AuthenticationFilter
           
        - id: API-GATEWAY
          uri: lb://API-GATEWAY
          predicates:
            - Path=/bs/employee/**
          filters:
           - AuthenticationFilter                           
           

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka