server:
  port: 8090
spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
      routes:
        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/sm/course/**

        - id: FEE-SERVICE
          uri: lb://FEE-SERVICE
          predicates:
            - Path=/sm/fee/**
            
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/sm/notify/**

        - id: SCHEDULER-SERVICE
          uri: lb://SCHEDULER-SERVICE
          predicates:
            - Path=/sm/schedule/**

        - id: STUDENTS-SERVICE
          uri: lb://STUDENTS-SERVICE
          predicates:
            - Path=/sm/students/**
          filters:
            - AuthenticationFilter
            
        - id: PERFORMANCE-SERVICE
          uri: lb://PERFORMANCE-SERVICE
          predicates:
            - Path=/sm/performance/**
          filters:
            - AuthenticationFilter         
            
        - id: TEACHER-SERVICE
          uri: lb://TEACHER-SERVICE
          predicates:
            - Path=/sm/teacher/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka