spring.cloud.azure.keyvault.secret.property-source-enabled=true
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://sm-properties.vault.azure.net/
server.port=8388
spring.profiles.active=native
spring.application.name=config-server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
spring.datasource.url=${db-url}
