server:
   port: 9904
      
spring:
     datasource:
       url: jdbc:postgresql://database-1.cr4ucs664vca.eu-north-1.rds.amazonaws.com:5432/DemoDB
       username: postgres
       password: postgres
     jpa:
       hibernate:
         ddl-auto: update
       show-sql: true
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost




